In [1]:
import numpy as np
import pandas as pd

In [13]:
from sklearn import metrics
from sklearn.model_selection import train_test_split

In [3]:
from sklearn import svm

In [6]:
iris = pd.read_csv("IRIS.csv")

In [11]:
iris.head()

sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [14]:
train,test = train_test_split(iris,test_size=0.25)

In [15]:
test

sepal_length  sepal_width  petal_length  petal_width          species
4             5.0          3.6           1.4          0.2      Iris-setosa
69            5.6          2.5           3.9          1.1  Iris-versicolor
100           6.3          3.3           6.0          2.5   Iris-virginica
106           4.9          2.5           4.5          1.7   Iris-virginica
23            5.1          3.3           1.7          0.5      Iris-setosa
99            5.7          2.8           4.1          1.3  Iris-versicolor
5             5.4          3.9           1.7          0.4      Iris-setosa
56            6.3          3.3           4.7          1.6  Iris-versicolor
97            6.2          2.9           4.3          1.3  Iris-versicolor
90            5.5          2.6           4.4          1.2  Iris-versicolor
102           7.1          3.0           5.9          2.1   Iris-virginica
14            5.8          4.0           1.2          0.2      Iris-setosa
103           6.3          2.9           5.6          1.8   Iris-virginica
105           7.6          3.0           6.6          2.1   Iris-virginica
138           6.0          3.0           4.8          1.8   Iris-virginica
53            5.5          2.3           4.0          1.3  Iris-versicolor
57            4.9          2.4           3.3          1.0  Iris-versicolor
78            6.0          2.9           4.5          1.5  Iris-versicolor
137           6.4          3.1           5.5          1.8   Iris-virginica
131           7.9          3.8           6.4          2.0   Iris-virginica
112           6.8          3.0           5.5          2.1   Iris-virginica
39            5.1          3.4           1.5          0.2      Iris-setosa
143           6.8          3.2           5.9          2.3   Iris-virginica
101           5.8          2.7           5.1          1.9   Iris-virginica
123           6.3          2.7           4.9          1.8   Iris-virginica
134           6.1          2.6           5.6          1.4   Iris-virginica
17            5.1          3.5           1.4          0.3      Iris-setosa
79            5.7          2.6           3.5          1.0  Iris-versicolor
11            4.8          3.4           1.6          0.2      Iris-setosa
75            6.6          3.0           4.4          1.4  Iris-versicolor
117           7.7          3.8           6.7          2.2   Iris-virginica
83            6.0          2.7           5.1          1.6  Iris-versicolor
66            5.6          3.0           4.5          1.5  Iris-versicolor
7             5.0          3.4           1.5          0.2      Iris-setosa
18            5.7          3.8           1.7          0.3      Iris-setosa
82            5.8          2.7           3.9          1.2  Iris-versicolor
107           7.3          2.9           6.3          1.8   Iris-virginica
94            5.6          2.7           4.2          1.3  Iris-versicolor

In [16]:
train_X=train[['sepal_length','sepal_width','petal_length','petal_width']]

In [17]:
train_y=train.species

In [18]:
train_X

sepal_length  sepal_width  petal_length  petal_width
135           7.7          3.0           6.1          2.3
110           6.5          3.2           5.1          2.0
8             4.4          2.9           1.4          0.2
128           6.4          2.8           5.6          2.1
20            5.4          3.4           1.7          0.2
..            ...          ...           ...          ...
64            5.6          2.9           3.6          1.3
52            6.9          3.1           4.9          1.5
46            5.1          3.8           1.6          0.2
60            5.0          2.0           3.5          1.0
145           6.7          3.0           5.2          2.3

[112 rows x 4 columns]

In [19]:
train_y


135     Iris-virginica
110     Iris-virginica
8          Iris-setosa
128     Iris-virginica
20         Iris-setosa
            ...       
64     Iris-versicolor
52     Iris-versicolor
46         Iris-setosa
60     Iris-versicolor
145     Iris-virginica
Name: species, Length: 112, dtype: object

In [20]:
test_X = test[['sepal_length','sepal_width','petal_length','petal_width']]
test_Y=test.species

In [21]:
model = svm.SVC()

In [22]:
model.fit(train_X,train_y)
pred = model.predict(test_X)

In [23]:
metrics.accuracy_score(pred,test_Y)

0.9210526315789473

In [25]:
from sklearn.metrics import confusion_matrix, classification_report

svm_cm = confusion_matrix(test_Y, pred)
svm_classification_report = classification_report(test_Y, pred)
print("SVM Confusion Matrix:\n", svm_cm)
print("SVM Classification Report:\n", svm_classification_report)

SVM Confusion Matrix:
 [[ 9  0  0]
 [ 0 13  1]
 [ 0  2 13]]
SVM Classification Report:
                  precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00         9
Iris-versicolor       0.87      0.93      0.90        14
 Iris-virginica       0.93      0.87      0.90        15

       accuracy                           0.92        38
      macro avg       0.93      0.93      0.93        38
   weighted avg       0.92      0.92      0.92        38

